export enum Genre {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  COMEDY = 'Comedy',
  DRAMA = 'Drama',
  HORROR = 'Horror',
  THRILLER = 'Thriller',
  SCI_FI = 'Sci-Fi',
  FANTASY = 'Fantasy',
  MYSTERY = 'Mystery',
  CRIME = 'Crime',
  ROMANCE = 'Romance',
  FAMILY = 'Family',
  ANIMATION = 'Animation',
  DOCUMENTARY = 'Documentary',
  HISTORY = 'History',
  WAR = 'War',
  WESTERN = 'Western',
  MUSIC = 'Music',
  SPORTS = 'Sports',
  BIOGRAPHY = 'Biography',
}

export const GenreIcons: Record<Genre, string> = {
  [Genre.ACTION]: 'zap',
  [Genre.ADVENTURE]: 'compass',
  [Genre.COMEDY]: 'smile',
  [Genre.DRAMA]: 'theater',
  [Genre.HORROR]: 'skull',
  [Genre.THRILLER]: 'eye',
  [Genre.SCI_FI]: 'rocket',
  [Genre.FANTASY]: 'sparkles',
  [Genre.MYSTERY]: 'search',
  [Genre.CRIME]: 'shield',
  [Genre.ROMANCE]: 'heart',
  [Genre.FAMILY]: 'users',
  [Genre.ANIMATION]: 'sparkles',
  [Genre.DOCUMENTARY]: 'camera',
  [Genre.HISTORY]: 'landmark',
  [Genre.WAR]: 'swords',
  [Genre.WESTERN]: 'hat-cowboy',
  [Genre.MUSIC]: 'music',
  [Genre.SPORTS]: 'trophy',
  [Genre.BIOGRAPHY]: 'user',
};
